version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parallelism: 4
    machine:
      image: cimg/base:2021.04
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
